# Generated by Django 4.0.6 on 2023-03-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicaltest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(max_length=128),
        ),
    ]
